# Generated by Django 5.1.3 on 2024-11-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_imageurl_books_isbn_books_title_books_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='imageURL',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
